// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type FileMonitorPendingOpen struct {
	Pid         uint32
	DirCategory uint8
	Pad         [3]uint8
}

// LoadFileMonitor returns the embedded CollectionSpec for FileMonitor.
func LoadFileMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FileMonitor: %w", err)
	}

	return spec, err
}

// LoadFileMonitorObjects loads FileMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileMonitorObjects
//	*FileMonitorPrograms
//	*FileMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFileMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorSpecs struct {
	FileMonitorProgramSpecs
	FileMonitorMapSpecs
}

// FileMonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorProgramSpecs struct {
	TracepointSyscallsSysEnterOpenat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysExitOpenat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat"`
}

// FileMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorMapSpecs struct {
	FileEvents   *ebpf.MapSpec `ebpf:"file_events"`
	PendingOpens *ebpf.MapSpec `ebpf:"pending_opens"`
	TrackedPids  *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// FileMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorObjects struct {
	FileMonitorPrograms
	FileMonitorMaps
}

func (o *FileMonitorObjects) Close() error {
	return _FileMonitorClose(
		&o.FileMonitorPrograms,
		&o.FileMonitorMaps,
	)
}

// FileMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorMaps struct {
	FileEvents   *ebpf.Map `ebpf:"file_events"`
	PendingOpens *ebpf.Map `ebpf:"pending_opens"`
	TrackedPids  *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *FileMonitorMaps) Close() error {
	return _FileMonitorClose(
		m.FileEvents,
		m.PendingOpens,
		m.TrackedPids,
	)
}

// FileMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorPrograms struct {
	TracepointSyscallsSysEnterOpenat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysExitOpenat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat"`
}

func (p *FileMonitorPrograms) Close() error {
	return _FileMonitorClose(
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysExitOpenat,
	)
}

func _FileMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filemonitor_x86_bpfel.o
var _FileMonitorBytes []byte
