// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadProcessTracer returns the embedded CollectionSpec for ProcessTracer.
func LoadProcessTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ProcessTracer: %w", err)
	}

	return spec, err
}

// LoadProcessTracerObjects loads ProcessTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessTracerObjects
//	*ProcessTracerPrograms
//	*ProcessTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcessTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessTracerSpecs struct {
	ProcessTracerProgramSpecs
	ProcessTracerMapSpecs
}

// ProcessTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessTracerProgramSpecs struct {
	TracepointSchedSchedProcessExit  *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork  *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_fork"`
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

// ProcessTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessTracerMapSpecs struct {
	ProcessEvents *ebpf.MapSpec `ebpf:"process_events"`
	TrackedPids   *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// ProcessTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessTracerObjects struct {
	ProcessTracerPrograms
	ProcessTracerMaps
}

func (o *ProcessTracerObjects) Close() error {
	return _ProcessTracerClose(
		&o.ProcessTracerPrograms,
		&o.ProcessTracerMaps,
	)
}

// ProcessTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessTracerMaps struct {
	ProcessEvents *ebpf.Map `ebpf:"process_events"`
	TrackedPids   *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *ProcessTracerMaps) Close() error {
	return _ProcessTracerClose(
		m.ProcessEvents,
		m.TrackedPids,
	)
}

// ProcessTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessTracerPrograms struct {
	TracepointSchedSchedProcessExit  *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork  *ebpf.Program `ebpf:"tracepoint__sched__sched_process_fork"`
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
}

func (p *ProcessTracerPrograms) Close() error {
	return _ProcessTracerClose(
		p.TracepointSchedSchedProcessExit,
		p.TracepointSchedSchedProcessFork,
		p.TracepointSyscallsSysEnterExecve,
	)
}

func _ProcessTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processtracer_x86_bpfel.o
var _ProcessTracerBytes []byte
