// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadSyscallTracer returns the embedded CollectionSpec for SyscallTracer.
func LoadSyscallTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SyscallTracer: %w", err)
	}

	return spec, err
}

// LoadSyscallTracerObjects loads SyscallTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SyscallTracerObjects
//	*SyscallTracerPrograms
//	*SyscallTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSyscallTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSyscallTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SyscallTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallTracerSpecs struct {
	SyscallTracerProgramSpecs
	SyscallTracerMapSpecs
}

// SyscallTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallTracerProgramSpecs struct {
	TracepointRawSyscallsSysEnter *ebpf.ProgramSpec `ebpf:"tracepoint__raw_syscalls__sys_enter"`
}

// SyscallTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallTracerMapSpecs struct {
	SyscallEvents *ebpf.MapSpec `ebpf:"syscall_events"`
	TrackedPids   *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// SyscallTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallTracerObjects struct {
	SyscallTracerPrograms
	SyscallTracerMaps
}

func (o *SyscallTracerObjects) Close() error {
	return _SyscallTracerClose(
		&o.SyscallTracerPrograms,
		&o.SyscallTracerMaps,
	)
}

// SyscallTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallTracerMaps struct {
	SyscallEvents *ebpf.Map `ebpf:"syscall_events"`
	TrackedPids   *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *SyscallTracerMaps) Close() error {
	return _SyscallTracerClose(
		m.SyscallEvents,
		m.TrackedPids,
	)
}

// SyscallTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallTracerPrograms struct {
	TracepointRawSyscallsSysEnter *ebpf.Program `ebpf:"tracepoint__raw_syscalls__sys_enter"`
}

func (p *SyscallTracerPrograms) Close() error {
	return _SyscallTracerClose(
		p.TracepointRawSyscallsSysEnter,
	)
}

func _SyscallTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalltracer_x86_bpfel.o
var _SyscallTracerBytes []byte
