// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTcpMonitor returns the embedded CollectionSpec for TcpMonitor.
func LoadTcpMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpMonitor: %w", err)
	}

	return spec, err
}

// LoadTcpMonitorObjects loads TcpMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpMonitorObjects
//	*TcpMonitorPrograms
//	*TcpMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorSpecs struct {
	TcpMonitorProgramSpecs
	TcpMonitorMapSpecs
}

// TcpMonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorProgramSpecs struct {
	KprobeTcpSendmsg               *ebpf.ProgramSpec `ebpf:"kprobe__tcp_sendmsg"`
	KretprobeTcpRecvmsg            *ebpf.ProgramSpec `ebpf:"kretprobe__tcp_recvmsg"`
	TracepointSockInetSockSetState *ebpf.ProgramSpec `ebpf:"tracepoint__sock__inet_sock_set_state"`
}

// TcpMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpMonitorMapSpecs struct {
	BytesEvents *ebpf.MapSpec `ebpf:"bytes_events"`
	SockToPid   *ebpf.MapSpec `ebpf:"sock_to_pid"`
	TcpEvents   *ebpf.MapSpec `ebpf:"tcp_events"`
	TrackedPids *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// TcpMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorObjects struct {
	TcpMonitorPrograms
	TcpMonitorMaps
}

func (o *TcpMonitorObjects) Close() error {
	return _TcpMonitorClose(
		&o.TcpMonitorPrograms,
		&o.TcpMonitorMaps,
	)
}

// TcpMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorMaps struct {
	BytesEvents *ebpf.Map `ebpf:"bytes_events"`
	SockToPid   *ebpf.Map `ebpf:"sock_to_pid"`
	TcpEvents   *ebpf.Map `ebpf:"tcp_events"`
	TrackedPids *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *TcpMonitorMaps) Close() error {
	return _TcpMonitorClose(
		m.BytesEvents,
		m.SockToPid,
		m.TcpEvents,
		m.TrackedPids,
	)
}

// TcpMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpMonitorPrograms struct {
	KprobeTcpSendmsg               *ebpf.Program `ebpf:"kprobe__tcp_sendmsg"`
	KretprobeTcpRecvmsg            *ebpf.Program `ebpf:"kretprobe__tcp_recvmsg"`
	TracepointSockInetSockSetState *ebpf.Program `ebpf:"tracepoint__sock__inet_sock_set_state"`
}

func (p *TcpMonitorPrograms) Close() error {
	return _TcpMonitorClose(
		p.KprobeTcpSendmsg,
		p.KretprobeTcpRecvmsg,
		p.TracepointSockInetSockSetState,
	)
}

func _TcpMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpmonitor_x86_bpfel.o
var _TcpMonitorBytes []byte
